#!/usr/bin/env bash
# This script edits the /etc/hosts file to block certain websites to prevent procrastination
# requires permissions to write /etc/hosts without sudo
# add .hosts/block file and .hosts/unblock files

CHOICE=$1
HOSTFILE='/etc/hosts'
LOC=$HOME'/Applications/Scripts'
CT=$(date '+%s')  #current time
BT=$(cat $LOC/hosts/blocktime) #Time until websites are blocked

RT=$(($BT-$CT)) #Time remaining

if [[ $CHOICE = '-b' ]] ; then  #Block distracting websites
    if [[ -n $2 ]]; then
      if [[ $2 -gt $RT ]]; then
        WAITTIME=$2
      else
        WAITTIME=$RT
      fi
    else
      echo "Specify how long the websites should remain blocked"
    fi

    cp $LOC/.hosts/block $HOSTFILE
    echo $(($CT+$WAITTIME)) > $LOC/.hosts/blocktime
    echo 'Websites have been blocked and can be unblocked after '$WAITTIME' seconds.'
elif [[ $CHOICE = '-u' ]]; then #unblock distracting websites
    if [[ $CT -gt $BT ]]; then
      cp $LOC/.hosts/unblock $HOSTFILE
      echo 'Websites have been cleared'
    else
      echo "Can't unblock websites. Focus!"
      echo  'Time remaining: '$(($BT-$CT))'sec.'
    fi
else
    echo 'Please choose to block or unblock (-b or -u) distracting websites.'
fi
